---
title: "매출액 회귀선 및 예상 총 매출액 도출 (가중회귀)_바이오_의무"
output:
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)

dr <- "C:/"
foldname <- paste0(dr, "Users/mazy4/Desktop")
setwd(foldname)

## 표본 파일 ##

dat1 <- read_xlsx("바이오의무표본조사O(22).xlsx", sheet = 1)

dat1 <- dat1[, c(2, 3, 5, 6, 7, 8, 10, 9)]
names(dat1)[1] <- "에너지원"
names(dat1)[2] <- "용량_kW"
names(dat1)[3] <- "사업체명"
names(dat1)[4] <- "신재생에너지_산업_분류_코드"
names(dat1)[5] <- "신재생에너지_분류_코드"
names(dat1)[6] <- "REC_발급_발전량_2018년_기준"
names(dat1)[7] <- "신재생에너지종사자"
names(dat1)[8] <- "신재생에너지_매출액_2018년_기준"
dat1$의무대상자여부 <- 0

# REC 발급 발전량 : 0인 row data는 삭제
dat1 <- dat1 %>% filter(REC_발급_발전량_2018년_기준 != 0)

dat1$에너지원[dat1$에너지원 == "LFG"] <- "바이오"
dat1$에너지원[dat1$에너지원 == "바이오가스"] <- "바이오"

#dat11 <- dat1 %>% filter(., 의무대상자여부 == 0)


## 의무대상자 파일 ##

# 주의사항 #
# 본 분석에서는 '의무대상자 제외'이므로 의무대상자 파일을 읽어들이는 과정은 생략함.

#dat12 <- read_xlsx("(E3) 발전업 data_바이오폐기물 발전량 추가.xlsx", sheet = 4, skip = 2)
#dat12 <- dat12[, 1:6]
#dat12$의무대상자여부 <- 1
#names(dat12)[1] <- "사업체명"
#names(dat12)[2] <- "에너지원"
#names(dat12)[3] <- "용량_kW"
#names(dat12)[4] <- "REC_발급_발전량_2018년_기준"
#names(dat12)[5] <- "신재생에너지_매출액_2018년_기준"
#names(dat12)[6] <- "신재생에너지종사자"
#dat12$신재생에너지_산업_분류_코드 <- dat12$신재생에너지_분류_코드 <- NA

# REC 발급 발전량 : 0인 row data는 삭제
#dat12 <- dat12 %>% filter(REC_발급_발전량_2018년_기준 != 0)

#dat12$에너지원[dat12$에너지원 == "폐기물에너지"] <- "폐기물"
#dat12$에너지원[dat12$에너지원 == "바이오에너지"] <- "바이오"

#dat1 <- rbind(data.frame(dat11), data.frame(dat12))

############################################################################################

dat1$에너지원_구분1 <- dat1$에너지원_구분2 <- dat1$에너지원

#dat1$에너지원_구분1[(dat1$에너지원_구분1 == "태양광") & (dat1$용량_kW < 100)] <- "태양광_100kW_미만"
#dat1$에너지원_구분1[(dat1$에너지원_구분1 == "태양광") & (dat1$용량_kW >= 100) & (dat1$용량_kW < 3000)] <- "태양광_100kW_이상_3MW_미만"
#dat1$에너지원_구분1[(dat1$에너지원_구분1 == "태양광") & (dat1$용량_kW >= 3000)] <- "태양광_3MW_이상"
#dat1$에너지원_구분1[(dat1$에너지원_구분1 == "수력") & (dat1$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat1$에너지원_구분1[(dat1$에너지원_구분1 == "수력") & (dat1$용량_kW < 1000)] <- "수력_1MW_미만"

#dat1$에너지원_구분2[(dat1$에너지원_구분2 == "태양광") & (dat1$용량_kW < 1000)] <- "태양광_1MW_미만"
#dat1$에너지원_구분2[(dat1$에너지원_구분2 == "태양광") & (dat1$용량_kW >= 1000)] <- "태양광_1MW_이상"
#dat1$에너지원_구분2[(dat1$에너지원_구분2 == "수력") & (dat1$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat1$에너지원_구분2[(dat1$에너지원_구분2 == "수력") & (dat1$용량_kW < 1000)] <- "수력_1MW_미만"

dat1 <- dat1[!is.na(dat1$에너지원), ] # NA 제거

#dat13 <- dat1[(substr(dat1$사업체명, 1, 7) == "한국농어촌공사") & (dat1$에너지원=="수력"),]
#dat1 <- dat1[!((substr(dat1$사업체명, 1, 7) == "한국농어촌공사") & (dat1$에너지원=="수력")),]

#dat13$사업체명 <- "한국농어촌공사"
#dat13 <- dat13 %>% group_by(., 에너지원, 사업체명, 신재생에너지_산업_분류_코드, 신재생에너지_분류_코드, 의무대상자여부) %>% summarize(.,용량_kW = sum(용량_kW), 발전매출액_백만원 = sum(발전매출액_백만원), 신재생에너지종사자 = sum(신재생에너지종사자))

#dat13$에너지원_구분1 <- dat13$에너지원_구분2 <- dat13$에너지원

#dat13$에너지원_구분1[(dat13$에너지원_구분1 == "수력") & (dat13$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat13$에너지원_구분1[(dat13$에너지원_구분1 == "수력") & (dat13$용량_kW < 1000)] <- "수력_1MW_미만"

#dat13$에너지원_구분2[(dat13$에너지원_구분2 == "수력") & (dat13$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat13$에너지원_구분2[(dat13$에너지원_구분2 == "수력") & (dat13$용량_kW < 1000)] <- "수력_1MW_미만"

#dat1 <- rbind(data.frame(dat1), data.frame(dat13))

############################################################################################

## 미조사 파일 ##

# 바이오의무표본조사X(24).xlsx
dat12 <- read_xlsx("바이오의무표본조사X(24).xlsx", sheet = 1)

dat12 <- dat12[, c(2, 3, 4, 14, 18, 6)]
names(dat12)[1] <- "에너지원"
names(dat12)[2] <- "용량_kW"
names(dat12)[3] <- "설비코드"
names(dat12)[4] <- "의무대상자여부"
names(dat12)[5] <- "REC_발급_발전량_2018년_기준"
names(dat12)[6] <- "사업체명"
dat12$의무대상자여부[is.na(dat12$의무대상자여부)] <- 0


# 미조사 파일
dat2 <- data.frame(dat12)

# REC 발급 발전량 : 0인 row data는 삭제
dat2 <- dat2 %>% filter(REC_발급_발전량_2018년_기준 != 0)

dat21 <- dat2[dat2$의무대상자여부==0,]
dat22 <- dat2[dat2$의무대상자여부==1,]

dat22 <- dat22 %>% group_by(에너지원,사업체명,의무대상자여부) %>% summarize(REC_발급_발전량_2018년_기준=sum(REC_발급_발전량_2018년_기준), 설비코드=NA, 용량_kW=NA)

dat2 <- rbind(data.frame(dat21), data.frame(dat22))

dat2$에너지원[dat2$에너지원 == "LFG"] <- "바이오"
dat2$에너지원[dat2$에너지원 == "바이오가스"] <- "바이오"
dat2$에너지원[dat2$에너지원 == "바이오매스"] <- "바이오"

dat2$에너지원_구분1 <- dat2$에너지원_구분2 <- dat2$에너지원

#dat2$에너지원_구분1[(dat2$에너지원_구분1 == "태양광") & (dat2$용량_kW < 100)] <- "태양광_100kW_미만"
#dat2$에너지원_구분1[(dat2$에너지원_구분1 == "태양광") & (dat2$용량_kW >= 100) & (dat2$용량_kW < 3000)] <- "태양광_100kW_이상_3MW_미만"
#dat2$에너지원_구분1[(dat2$에너지원_구분1 == "태양광") & (dat2$용량_kW >= 3000)] <- "태양광_3MW_이상"
#dat2$에너지원_구분1[(dat2$에너지원_구분1 == "수력") & (dat2$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat2$에너지원_구분1[(dat2$에너지원_구분1 == "수력") & (dat2$용량_kW < 1000)] <- "수력_1MW_미만"

#dat2$에너지원_구분2[(dat2$에너지원_구분2 == "태양광") & (dat2$용량_kW < 1000)] <- "태양광_1MW_미만"
#dat2$에너지원_구분2[(dat2$에너지원_구분2 == "태양광") & (dat2$용량_kW >= 1000)] <- "태양광_1MW_이상"
#dat2$에너지원_구분2[(dat2$에너지원_구분2 == "수력") & (dat2$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat2$에너지원_구분2[(dat2$에너지원_구분2 == "수력") & (dat2$용량_kW < 1000)] <- "수력_1MW_미만"

dat2 <- dat2[!is.na(dat2$에너지원),] # NA 제거

#dat23 <- dat2[(substr(dat2$사업체명, 1, 7) == "한국농어촌공사") & (dat2$에너지원=="수력"),]
#dat2 <- dat2[!((substr(dat2$사업체명, 1, 7) == "한국농어촌공사") & (dat2$에너지원=="수력")),]

#dat23$사업체명 <- "한국농어촌공사"

#dat23 <- dat23 %>% group_by(., 에너지원, 사업체명, 의무대상자여부) %>% summarize(.,용량_kW = sum(용량_kW))

#dat23$설비코드 <- NA
#dat23$사업년도 <- NA

#dat23$에너지원_구분1 <- dat23$에너지원_구분2 <- dat23$에너지원

#dat23$에너지원_구분1[(dat23$에너지원_구분1 == "수력") & (dat23$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat23$에너지원_구분1[(dat23$에너지원_구분1 == "수력") & (dat23$용량_kW < 1000)] <- "수력_1MW_미만"

#dat23$에너지원_구분2[(dat23$에너지원_구분2 == "수력") & (dat23$용량_kW >= 1000)] <- "수력_1MW_이상"
#dat23$에너지원_구분2[(dat23$에너지원_구분2 == "수력") & (dat23$용량_kW < 1000)] <- "수력_1MW_미만"

#dat2 <- rbind(data.frame(dat2), data.frame(dat23))
```

# 조사갯수

## 의무대상자여부별 에너지원별 조사 갯수

```{r}
tmptmp1 <- dat1 %>% group_by(.,에너지원,의무대상자여부) %>% summarize(n=n())
tmptmp2 <- dat2 %>% group_by(.,에너지원,의무대상자여부) %>% summarize(n=n())

names(tmptmp1)[3] <- "조사 사업체수"
names(tmptmp2)[3] <- "전체 사업체수"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원) %>% kable %>% kable_styling
```

## 의무대상자여부별 에너지원별 조사 갯수 (구분1) (매출액 추정에 쓰일 분류)

```{r}
tmptmp1 <- dat1 %>% group_by(.,에너지원_구분1,의무대상자여부) %>% summarize(n=n())
tmptmp2 <- dat2 %>% group_by(.,에너지원_구분1,의무대상자여부) %>% summarize(n=n())

names(tmptmp1)[3] <- "조사 사업체수"
names(tmptmp2)[3] <- "전체 사업체수"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원_구분1) %>% kable %>% kable_styling
```

## 의무대상자여부별 에너지원별 조사 갯수 (구분2) (종사자수 추정에 쓰일 분류)

```{r}
tmptmp1 <- dat1 %>% group_by(.,에너지원_구분2,의무대상자여부) %>% summarize(n=n())
tmptmp2 <- dat2 %>% group_by(.,에너지원_구분2,의무대상자여부) %>% summarize(n=n())

names(tmptmp1)[3] <- "조사 사업체수"
names(tmptmp2)[3] <- "전체 사업체수"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원_구분2) %>% kable %>% kable_styling
```

# 조사 사업체 용량 합 (단위 : kW) 

## 의무대상자여부별 에너지원별 조사 갯수

```{r}
tmptmp1 <- dat1 %>% group_by(.,의무대상자여부,에너지원) %>% summarize(sum(REC_발급_발전량_2018년_기준))
tmptmp2 <- dat2 %>% group_by(.,의무대상자여부,에너지원) %>% summarize(sum(REC_발급_발전량_2018년_기준))

names(tmptmp1)[3] <- "조사 사업체 용량 합 (MWh)"
names(tmptmp2)[3] <- "전체 사업체 용량 합 (MWh)"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원) %>% kable %>% kable_styling
```

## 의무대상자여부별 에너지원별 조사 갯수 (구분1) (매출액 추정에 쓰일 분류)

```{r}
tmptmp1 <- dat1 %>% group_by(.,의무대상자여부,에너지원_구분1) %>% summarize(sum(REC_발급_발전량_2018년_기준))
tmptmp2 <- dat2 %>% group_by(.,의무대상자여부,에너지원_구분1) %>% summarize(sum(REC_발급_발전량_2018년_기준))

names(tmptmp1)[3] <- "조사 사업체 용량 합 (MWh)"
names(tmptmp2)[3] <- "전체 사업체 용량 합 (MWh)"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원_구분1) %>% kable %>% kable_styling
```

## 의무대상자여부별 에너지원별 조사 갯수 (구분2) (종사자수 추정에 쓰일 분류)

```{r}
tmptmp1 <- dat1 %>% group_by(.,의무대상자여부,에너지원_구분2) %>% summarize(sum(REC_발급_발전량_2018년_기준))
tmptmp2 <- dat2 %>% group_by(.,의무대상자여부,에너지원_구분2) %>% summarize(sum(REC_발급_발전량_2018년_기준))

names(tmptmp1)[3] <- "조사 사업체 용량 합 (MWh)"
names(tmptmp2)[3] <- "전체 사업체 용량 합 (MWh)"

merge(tmptmp1, tmptmp2) %>% arrange(에너지원_구분2) %>% kable %>% kable_styling
```

# 결과

## 발전매출액 추정.

방법 : 가중회귀 (weight = 1/용량)

```{r results='asis', fig.width = 3, fig.height=2}
a <- dat1 %>% group_by(.,에너지원_구분1) %>% count %>% {.$에너지원_구분1}

for(i in a){
      tmp_dat1 <- dat1 %>%
        filter(., 에너지원_구분1 == i)
      tmp_dat21 <- dat2 %>%
        filter(., 에너지원_구분1 == i) %>%
        filter(., 의무대상자여부 == 0)
      tmp_dat22 <- dat2 %>%
        filter(., 에너지원_구분1 == i) %>%
        filter(., 의무대상자여부 == 1)
      
      w_s <- (1/tmp_dat1$REC_발급_발전량_2018년_기준)
      tmp_lm <- lm(신재생에너지_매출액_2018년_기준 ~ REC_발급_발전량_2018년_기준, data = tmp_dat1, weights = w_s)
      coef_ <- tmp_lm$coefficients
      coef_[is.na(coef_)] <- 0
      
      미의무_조사_원래_총_매출액 <- sum(tmp_dat1 %>% filter(.,의무대상자여부 == 0) %>% {.$신재생에너지_매출액_2018년_기준})
      의무_조사_원래_총_매출액 <- sum(tmp_dat1 %>% filter(.,의무대상자여부 == 1) %>% {.$신재생에너지_매출액_2018년_기준})
      
      X11 <- cbind(1,tmp_dat1 %>%
                     filter(.,의무대상자여부 == 0) %>%
                     {.$REC_발급_발전량_2018년_기준})
      res11 <- (tmp_dat1 %>%
                  filter(.,의무대상자여부 == 0) %>%
                  {.$발전매출액_백만원}) - (X11 %*% coef_)
      미의무_조사_원래_추정_차 <- sum(res11)
      if(dim(tmp_dat1 %>% filter(.,의무대상자여부 == 0))[1] == 0){미의무_조사_원래_추정_차 <- 0}
      
      X12 <- cbind(1,tmp_dat1 %>%
                     filter(.,의무대상자여부 == 1) %>%
                     {.$REC_발급_발전량_2018년_기준})
      res12 <- (tmp_dat1 %>%
                  filter(.,의무대상자여부 == 1) %>%
                  {.$신재생에너지_매출액_2018년_기준}) - (X12 %*% coef_)
      의무_조사_원래_추정_차 <- sum(res12)
      if(dim(tmp_dat1 %>% filter(.,의무대상자여부 == 1))[1] == 0){의무_조사_원래_추정_차 <- 0}

      X21 <- cbind(1,tmp_dat21$REC_발급_발전량_2018년_기준)
      y21 <- (X21 %*% coef_)
      y21[y21<0] <- 0
      미의무_조사X_추정_총_매출액 <- sum(y21)
      if(dim(tmp_dat21)[1] == 0){미의무_조사X_추정_총_매출액 <- 0}

      X22 <- cbind(1,tmp_dat22$REC_발급_발전량_2018년_기준)
      y22 <- (X22 %*% coef_)
      y22[y22<0] <- 0
      의무_조사X_추정_총_매출액 <- sum(y22)
      if(dim(tmp_dat22)[1] == 0){의무_조사X_추정_총_매출액 <- 0}

      data.frame(항목 = c("에너지 원",
                        "회귀선",
                        "조사 & 미의무대상자 실제 총 매출액",
                        "조사 & 미의무대상자 (실제 - 추정)",
                        "조사 & 미의무대상자 (실제 - 추정)/실제",
                        "조사 & 의무대상자 실제 총 매출액",
                        "조사 & 의무대상자 (실제 - 추정)",
                        "조사 & 의무대상자 (실제 - 추정)/실제",
                        "미조사 & 미의무대상자 추정 총 매출액",
                        "미조사 & 의무대상자 추정 총 매출액",
                        "미의무대상자 (조사 실제 총 매출액 + 미조사 추정 총 매출액)",
                        "의무대상자 (조사 실제 총 매출액 + 미조사 추정 총 매출액)"),
                   내용 = c(i,
                          paste("E(신재생에너지_매출액_2018년_기준) =", round(coef_[1],7), "+",
                                round(coef_[2],7), "* REC_발급_발전량_2018년_기준" ),
                          round(미의무_조사_원래_총_매출액,2),
                          round(미의무_조사_원래_추정_차,2),
                          round(미의무_조사_원래_추정_차 / 미의무_조사_원래_총_매출액,7),
                          round(의무_조사_원래_총_매출액,2),
                          round(의무_조사_원래_추정_차,2),
                          round(의무_조사_원래_추정_차/의무_조사_원래_총_매출액,7),
                          round(미의무_조사X_추정_총_매출액,2),
                          round(의무_조사X_추정_총_매출액,2),
                          round(미의무_조사_원래_총_매출액 + 미의무_조사X_추정_총_매출액,2),
                          round(의무_조사_원래_총_매출액 + 의무_조사X_추정_총_매출액,2)
                          )) %>% kable %>% kable_styling %>% print
      
      cat("\n")
      
      X1 <- cbind(1,tmp_dat1$REC_발급_발전량_2018년_기준)
      tmp_dat1$잔차 <- (w_s^.5)*(tmp_dat1$신재생에너지_매출액_2018년_기준 - (X1 %*% coef_))
      tmp_dat1$abs_잔차 <- abs(tmp_dat1$잔차)
      
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = 신재생에너지_매출액_2018년_기준)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = coef_[1], slope = coef_[2]))
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = 잔차)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = 0, slope = 0))
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = abs_잔차)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = 0, slope = 0))
}

```

## 종사자 수 추정.

방법 : 가중회귀 (weight = 1/용량)

```{r results='asis', fig.width = 3, fig.height=2}
a <- dat1 %>% group_by(.,에너지원_구분2) %>% count %>% {.$에너지원_구분2}

for(i in a){
  cat("#################################################################\n")
      tmp_dat1 <- dat1 %>%
        filter(., 에너지원_구분2 == i)
      tmp_dat21 <- dat2 %>%
        filter(., 에너지원_구분2 == i) %>%
        filter(., 의무대상자여부 == 0)
      tmp_dat22 <- dat2 %>%
        filter(., 에너지원_구분2 == i) %>%
        filter(., 의무대상자여부 == 1)
      
      w_s <- (1/tmp_dat1$REC_발급_발전량_2018년_기준)
      tmp_lm <- lm(신재생에너지종사자 ~ REC_발급_발전량_2018년_기준, data = tmp_dat1, weights = w_s)
      coef_ <- tmp_lm$coefficients
      coef_[is.na(coef_)] <- 0
      
      미의무_조사_원래_총_종사자수 <- sum(tmp_dat1 %>% filter(.,의무대상자여부 == 0) %>% {.$신재생에너지종사자})
      의무_조사_원래_총_종사자수 <- sum(tmp_dat1 %>% filter(.,의무대상자여부 == 1) %>% {.$신재생에너지종사자})
      
      X11 <- cbind(1,tmp_dat1 %>%
                     filter(.,의무대상자여부 == 0) %>%
                     {.$REC_발급_발전량_2018년_기준})
      res11 <- (tmp_dat1 %>%
                  filter(.,의무대상자여부 == 0) %>%
                  {.$신재생에너지종사자}) - (X11 %*% coef_)
      미의무_조사_원래_추정_차 <- sum(res11)
      if(dim(tmp_dat1 %>% filter(.,의무대상자여부 == 0))[1] == 0){미의무_조사_원래_추정_차 <- 0}
      
      X12 <- cbind(1,tmp_dat1 %>%
                     filter(.,의무대상자여부 == 1) %>%
                     {.$REC_발급_발전량_2018년_기준})
      res12 <- (tmp_dat1 %>%
                  filter(.,의무대상자여부 == 1) %>%
                  {.$신재생에너지종사자}) - (X12 %*% coef_)
      의무_조사_원래_추정_차 <- sum(res12)
      if(dim(tmp_dat1 %>% filter(.,의무대상자여부 == 1))[1] == 0){의무_조사_원래_추정_차 <- 0}

      X21 <- cbind(1,tmp_dat21$REC_발급_발전량_2018년_기준)
      y21 <- (X21 %*% coef_)
      y21[y21<0] <- 0
      미의무_조사X_추정_총_종사자수 <- sum(y21)
      if(dim(tmp_dat21)[1] == 0){미의무_조사X_추정_총_종사자수 <- 0}

      X22 <- cbind(1,tmp_dat22$REC_발급_발전량_2018년_기준)
      y22 <- (X22 %*% coef_)
      y22[y22<0] <- 0
      의무_조사X_추정_총_종사자수 <- sum(y22)
      if(dim(tmp_dat22)[1] == 0){의무_조사X_추정_총_종사자수 <- 0}

      data.frame(항목 = c("에너지 원",
                        "회귀선",
                        "조사 & 미의무대상자 실제 총 종사자수",
                        "조사 & 미의무대상자 (실제 - 추정)",
                        "조사 & 미의무대상자 (실제 - 추정)/실제",
                        "조사 & 의무대상자 실제 총 종사자수",
                        "조사 & 의무대상자 (실제 - 추정)",
                        "조사 & 의무대상자 (실제 - 추정)/실제",
                        "미조사 & 미의무대상자 추정 총 종사자수",
                        "미조사 & 의무대상자 추정 총 종사자수",
                        "미의무대상자 (조사 실제 총 종사자수 + 미조사 추정 총 종사자수)",
                        "의무대상자 (조사 실제 총 종사자수 + 미조사 추정 총 종사자수)"),
                   내용 = c(i,
                          paste("E(발전종사자수_명) =", round(coef_[1],7), "+", round(coef_[2],7),
                                "* REC_발급_발전량_2018년_기준" ),
                          round(미의무_조사_원래_총_종사자수,2),
                          round(미의무_조사_원래_추정_차,2),
                          round(미의무_조사_원래_추정_차 / 미의무_조사_원래_총_종사자수,7),
                          round(의무_조사_원래_총_종사자수,2),
                          round(의무_조사_원래_추정_차,2),
                          round(의무_조사_원래_추정_차/의무_조사_원래_총_종사자수,7),
                          round(미의무_조사X_추정_총_종사자수,2),
                          round(의무_조사X_추정_총_종사자수,2),
                          round(미의무_조사_원래_총_종사자수 + 미의무_조사X_추정_총_종사자수,2),
                          round(의무_조사_원래_총_종사자수 + 의무_조사X_추정_총_종사자수,2)
                          )) %>% kable %>% kable_styling %>% print
      
      cat("\n")
      
      X1 <- cbind(1,tmp_dat1$REC_발급_발전량_2018년_기준)
      tmp_dat1$잔차 <- (w_s^.5)*(tmp_dat1$신재생에너지종사자 - (X1 %*% coef_))
      tmp_dat1$abs_잔차 <- abs(tmp_dat1$잔차)
      
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = 신재생에너지종사자)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = coef_[1], slope = coef_[2]))
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = 잔차)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = 0, slope = 0))
      print(ggplot(data = tmp_dat1, aes(x = REC_발급_발전량_2018년_기준,
                                        y = abs_잔차)) +
              geom_point() + theme_bw() + geom_abline(
                intercept = 0, slope = 0))
      
      cat("#################################################################\n")
}

```