---
title: "종사자수 추정(평균)"
author: "김동현"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=5, fig.height=3)
library(knitr)
library(kableExtra)
library(tidyverse)
library(readxl)
library(ggplot2)
library(doBy)
```


```{r, include=FALSE}
## 산업분류표 만들기
산업분류 <- read_xlsx("C:/Users/mazy4/Desktop/소분류별_상위기업제외/data/신재생에너지 산업 특수분류체계 연계 KSIC(9차-10차)_E3_20200323(del).xlsx", skip = 1)
산업분류 <- 산업분류[, -c(9, 10)] # 비고 항 제거
산업분류 <- 산업분류[-nrow(산업분류), ] # 마지막 행 제거
names(산업분류) <- c("대","중","소","세","세세_9차","KSIC코드_9차","세세","KSIC코드")

## NA 부분 모두 밀어서 이름 부여
for(i in 1:(dim(산업분류)[1])){
  if(is.na(산업분류$대[i])){
    산업분류$대[i] <- 산업분류$대[i-1]}
  if(is.na(산업분류$중[i])){
    산업분류$중[i] <- 산업분류$중[i-1]}
  if(is.na(산업분류$소[i])){
    산업분류$소[i] <- 산업분류$소[i-1]}
  if(is.na(산업분류$세[i])){
    산업분류$세[i] <- 산업분류$세[i-1]}
  if(is.na(산업분류$세세_9차[i])){
    산업분류$세세_9차[i] <- 산업분류$세세_9차[i-1]}
  if(is.na(산업분류$KSIC코드_9차[i])){
    산업분류$KSIC코드_9차[i] <- 산업분류$KSIC코드_9차[i-1]}
}

write_file_name <- "산업분류표_대기업포함.csv"
write_csv(산업분류,paste("./",write_file_name,sep=""))

## 같은 소분류 내에 KSIC이 몇 번 중복 되는지?

소분류별_KSIC_count <- 산업분류 %>% group_by(., 대, 중, 소, KSIC코드) %>% count()

## 같은 KSIC이 몇 개의 서로 다른 소분류에 중복 되는지?

KSIC_count_가중치 <- 소분류별_KSIC_count %>% group_by(., KSIC코드) %>% count %>% mutate(., 가중치_n역수_ = 1/n)

소분류별_KSIC_count <- 소분류별_KSIC_count[,-5] %>% merge(.,KSIC_count_가중치, all.x=TRUE)
```

# 소분류 & 에너지원 매칭표

```{r}
소분류_에너지원_매칭표 <- read_xlsx("C:/Users/mazy4/Desktop/소분류별_상위기업제외/data/소분류_에너지원_매칭_200323.xlsx",sheet=1)
소분류_에너지원_매칭표 %>% kable %>% kable_styling
```

# 사업체수 추정

```{r, include = FALSE}
사업체수추정표 <- read_xlsx("C:/Users/mazy4/Desktop/소분류별_상위기업제외/data/2019년도 전후방산업 스크린조사 完_191210_종사자 규모별(수정).xlsx", sheet=6, skip=3)[1:102,c(5,6,17)]
colnames(사업체수추정표) <- c("KSIC코드","조사모집단수","적격률")
소분류별_KSIC_count_사업체수 <- 소분류별_KSIC_count %>% merge(., 사업체수추정표, all.x=TRUE)
소분류별_KSIC_count_사업체수$사업체수추정 <- 소분류별_KSIC_count_사업체수$가중치_n역수_ * 소분류별_KSIC_count_사업체수$조사모집단수 * 소분류별_KSIC_count_사업체수$적격률
```

## 세세분류별 결과 사업체수 추정 결과

```{r}
소분류별_KSIC_count_사업체수 %>% kable %>% kable_styling
```

## 세세분류별 결과를 소분류로 묶었을 때

```{r}
소분류별_추정사업체수 <- 소분류별_KSIC_count_사업체수 %>% group_by(., 대, 중, 소) %>% summarize(., 추정사업체수=sum(사업체수추정, na.rm=TRUE))
소분류별_추정사업체수 %>% kable %>% kable_styling
```

## 전체 종사자수 다 한꺼번에 dot plot

```{r, include = FALSE}
조사결과 <- read_xlsx("C:/Users/mazy4/Desktop/소분류별_상위기업제외/data/완료_2019년도 신재생에너지 전후방산업_본조사 data_0228(745)_17년도 실적 매칭 + 제조 상위기업.xlsx",sheet=2,skip=3)
proc_조사결과 <- 조사결과[,c(2,4,7,8,14)]
names(proc_조사결과) <- c("상위업체", "업체명", "KSIC코드", "종사자규모", "총_종사자수_2018")
proc_조사결과$상위업체[is.na(proc_조사결과$상위업체)] <- 0
proc_조사결과 <- proc_조사결과 %>% filter(., 상위업체 != 1)
```

```{r}
library(ggplot2)
ggplot(proc_조사결과, aes(x = 총_종사자수_2018)) + geom_dotplot(method="histodot", binwidth = 400) + theme_bw()
```

## 추정 종사자수

```{r, results = "asis"}
소_unique <- unique(소분류별_KSIC_count_사업체수$소)

# 비중 불러들이기(추가된 코드)
중복_KSIC_종사자 <- read_xlsx("C:/Users/mazy4/Desktop/소분류별_상위기업제외/종사자수_소분류별/중복_KSIC_data_종사자_표1.xlsx")

# 소_i <- 소_unique[1]
tmp_df <- data.frame()
for(소_i in 소_unique){
  tmp_소분류별_KSIC_count_사업체수 <- 소분류별_KSIC_count_사업체수 %>% filter(., 소 == 소_i)
  tmp_소분류_에너지원_매칭표 <- 소분류_에너지원_매칭표 %>% filter(., 소 == 소_i)
  tmp_proc_조사결과 <- proc_조사결과 %>%
    filter(., KSIC코드 %in% tmp_소분류별_KSIC_count_사업체수$KSIC코드)
  
  # 종사자수 수정(추가된 코드)
  temp1 <- 중복_KSIC_종사자[중복_KSIC_종사자$소분류 == 소_i,]
  총_종사자수 <- c(tmp_proc_조사결과$총_종사자수_2018, temp1$종사자수_수정)
  
  if(dim(tmp_proc_조사결과)[1] == 0){
    data.frame(
      항목 = c(
        "소분류",
        "매칭 에너지원",
        "해당되는 KSIC",
        "추정 사업체 수",
        "해당하는 sample 수",
        "추정불가"
        ),
      내용 = c(
        소_i,
        tmp_소분류_에너지원_매칭표$에너지원 %>% sort %>%
          paste(., collapse = ", "),
        tmp_소분류별_KSIC_count_사업체수$KSIC코드 %>% unique %>% sort %>%
          paste(., collapse = ", "),
        round(sum(tmp_소분류별_KSIC_count_사업체수$사업체수추정),0),
        0,
        "추정불가"
        )
      ) %>% kable() %>% kable_styling() %>% print
    } else {
      표본_평균_종사자수 <- mean(총_종사자수) # 총_종사자수 -> 변수 수정하였음.
      추정_총_종사자수 <- 표본_평균_종사자수*(sum(tmp_소분류별_KSIC_count_사업체수$사업체수추정) - sum(1/tmp_소분류별_KSIC_count_사업체수$가중치_n역수_)) # sum 부분 수정
      data.frame(
        항목 = c(
          "소분류",
          "매칭 에너지원",
          "해당되는 KSIC",
          "추정 사업체 수",
          "해당하는 sample 수",
          "평균",
          "추정 총 종사자수"
          ),
        내용 = c(
          소_i,
          tmp_소분류_에너지원_매칭표$에너지원 %>% sort %>%
            paste(., collapse = ", "),
          tmp_소분류별_KSIC_count_사업체수$KSIC코드 %>% unique %>% sort %>%
            paste(., collapse = ", "),
          round(sum(tmp_소분류별_KSIC_count_사업체수$사업체수추정),0),
          dim(tmp_proc_조사결과)[1],
          round(표본_평균_종사자수,5),
          round(추정_총_종사자수,5)
          )
        ) %>% kable() %>% kable_styling() %>% print
      
      print(
        ggplot(
          tmp_proc_조사결과, aes(x = 총_종사자수_2018)) +
          geom_dotplot(method="histodot") +
          geom_vline(xintercept = 표본_평균_종사자수, linetype = 2) + 
          theme_bw()
        )
      tmp_df <- rbind(
        tmp_df,
        data.frame(
          소 = 소_i,
          추정_총_종사자수 = 추정_총_종사자수)
        )
      }
  cat("\n############################################################\n")
}
```

## 소분류별 종사자수 결과

```{r}
소분류별_추정사업체수[,1:3] %>%
  merge(., tmp_df) %>%
  group_by(., 대, 중, 소) %>%
  summarise(., 추정_종사자수 = sum(추정_총_종사자수))%>%
  kable() %>% kable_styling()
```

## 중분류별 에너지원별 종사자수 결과 

```{r}
소분류별_추정사업체수[,1:3] %>%
  merge(., 소분류_에너지원_매칭표) %>%
  merge(., tmp_df) %>%
  group_by(., 대, 중, 에너지원) %>%
  summarise(., 추정_종사자수 = sum(추정_총_종사자수 * 가중치)) %>%
  kable() %>% kable_styling()
```

## 대분류별 에너지원별 종사자수 결과 

```{r}
소분류별_추정사업체수[,1:3] %>%
  merge(., 소분류_에너지원_매칭표) %>%
  merge(., tmp_df) %>%
  group_by(., 대, 에너지원) %>%
  summarise(., 추정_종사자수 = sum(추정_총_종사자수 * 가중치)) %>%
  kable() %>% kable_styling()
```